### ISSUE TITLE
Problems with `TaskLoader._compute_x1x2_direction` 

### ISSUE THREAD

**Issue by davidwyld** [davidwilby/deepsensor#3]
Sorry I should have picked these up in the pull request where it was introduced, but only noticed problems now that we've updated from main and have all the tests running.

Unfortunately this method is causing several of the tests to fail because of the way it handles pandas context and target data.

I've opened this issue since I'm pretty confused about this function and suspect that it's not behaving as intended.

https://github.com/davidwilby/deepsensor/blob/79afa1263f392cc8f2a86221f144c18fcaddb97f/deepsensor/data/loader.py#L838-L882

So:
+ I will update the docstring here (on a PR) to more accurately reflect what the method is returning,
+ this method fails in the case that either `self.context` or `self.target` are pandas dataframes or series (or anything that isn't an xr dataset or dataarray) because the `coord_*` variables aren't set, then are referred to later in the method. This causes `TaskLoader.__init__` to fail when using pandas dataarrays. If this is not to be used for those types of data, we should handle and exit the method gracefully.
+ I noticed that the dictionary that is returned just includes the values of `{x1,x2}_ascend` from the last iteration of the loop, which doesn't seem like the desired behaviour, and if it is, it's just wasting the computation of the other iterations of the loop. What's the desired outcome here?
+ Assigning `True` to `{x1,x2}_ascend` for each loop before the `if` statements is a bit odd, and the `if` statements themselves are a bit strange since they cover every case except where the two values being compared are equal, in which case these could be more succinctly expressed by, e.g. `x1_ascend=True if coord_x1_left <= coord_x1_right else False`

Sorry for not catching this earlier, my bad.

**Comment by MartinSJRogers** [comment]
Thanks @davidwilby, I added a TODO here because I wasn't sure how to handle scenarios where we were not dealing with an xarray but wanted to identify the direction of the coordinates. 

My feeling is that this code can be removed, because we are finding out the direction of the coordinates to prevent errors during stitching, and we will only ever stitch with xarrays. But I am still a little unclear how predictions occur when using pandas (as I have never worked with an example that uses pandas), so we should double check this with Tom.
